superpoint_extractor:
  onnx_file: "/root/workspace/hfe/model/superpoint_v1_sim_int32.onnx"
  engine_file: "/root/workspace/hfe/model/superpoint_v1_sim_int32.engine"
  enable_fp16: 1
  enable_dla : 0
  input_width: 320
  input_height: 160 # width and height should be the multiple of 8
  cuda_nms: 1 #if 1 use cuda to do NMS, else use CPU
  input_tensor_names: 
    - "input"
  output_tensor_names:
    - "scores"
    - "descriptors"
  threshold: 0.15
  nms_radius: 20
  max_point: 100
  test_image: "/root/workspace/hfe/test_data/superpoint_test_out0001_resize.png"
